version: 2

jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build -t black3r/gcloud-docker-builder:$CIRCLE_SHA1 .
      - run:
          name: Push docker image to dockerhub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push black3r/gcloud-docker-builder:$CIRCLE_SHA1
